# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kun6mb7_OhyeEIe4_BUpiJSsenoKpybi
"""

import streamlit as st
import base64
from pathlib import Path


st.set_page_config(
    page_title="Dokumen PDF",
    page_icon="📄",
    layout="wide"
)


st.title("Dokumen PDF")
st.write("Dokumen dapat dibaca langsung melalui halaman ini.")


pdf_path = Path("pdf/dokumen.pdf")


if not pdf_path.exists():

    st.error("File PDF tidak ditemukan.")

    st.info(
        "Pastikan file berada di folder "
        "`pdf/` dengan nama `dokumen.pdf`."
    )

else:


    with open(pdf_path, "rb") as pdf_file:
        pdf_bytes = pdf_file.read()

    st.download_button(
        label="⬇️ Download PDF",
        data=pdf_bytes,
        file_name="dokumen.pdf",
        mime="application/pdf"
    )

    st.divider()


    base64_pdf = base64.b64encode(pdf_bytes).decode("utf-8")

    pdf_display = f"""
    <iframe
        src="data:application/pdf;base64,{base64_pdf}"
        width="100%"
        height="900"
        style="border: none;">
    </iframe>
    """

    st.markdown(
        pdf_display,
        unsafe_allow_html=True
    )

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit

