# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kun6mb7_OhyeEIe4_BUpiJSsenoKpybi
"""

import streamlit as st

# =========================
# KONFIGURASI
# =========================

st.set_page_config(
    page_title="Dokumen PDF",
    page_icon="📄",
    layout="wide"
)

# =========================
# JUDUL
# =========================

st.title("📄 Dokumen PDF")
st.write("Dokumen dapat dibaca langsung melalui halaman ini.")

# =========================
# URL PDF DI GITHUB
# =========================

pdf_url = "https://raw.githubusercontent.com/USERNAME/REPOSITORY/main/pdf/dokumen.pdf"

# =========================
# TAMPILKAN PDF
# =========================

st.markdown(
    f"""
    <iframe
        src="{pdf_url}"
        width="100%"
        height="900px"
        style="border: none;">
    </iframe>
    """,
    unsafe_allow_html=True
)

# =========================
# LINK BUKA PDF
# =========================

st.markdown(
    f"""
    <a href="{pdf_url}" target="_blank">
        📄 Buka PDF di tab baru
    </a>
    """,
    unsafe_allow_html=True
)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit

