# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7XD3Zay6v111V8_gfvNFFemuQv4zjvD
"""

import streamlit as st
from pathlib import Path

st.set_page_config(
    page_title="ASDP Dashboard",
    page_icon="🎬",
    layout="wide"
)


st.title("🎬 ASDP Dashboard")

st.write(
    "Video dapat diputar langsung melalui halaman Streamlit."
)

video_path = Path("video/video_dashboard.mp4")

if not video_path.exists():

    st.error("Video tidak ditemukan.")

    st.info(
        "Pastikan file video berada di folder `video/` "
        "dengan nama `video_dashboard.mp4`."
    )

else:


    st.video(
        str(video_path),
        autoplay=False,
        loop=False,
        muted=False
    )

    st.success("Video berhasil dimuat.")

